SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) TOTAL_SALES
FROM AUTHOR
INNER JOIN(
    SELECT BOOK.*, PRICE * SALES TOTAL_SALES
    FROM BOOK
    INNER JOIN(
        -- 22년 1월에 판매된 BOOK_ID별 도서 판매량
        SELECT BOOK_ID, SUM(SALES) SALES FROM BOOK_SALES
        WHERE SUBSTRING(SALES_DATE, 1, 7) = '2022-01'
        GROUP BY BOOK_ID
    ) BOOK_SALES
    ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
) B
ON AUTHOR.AUTHOR_ID = B.AUTHOR_ID
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;