-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ', STREET_ADDRESS2) 전체주소, CONCAT(LEFT(TLNO, 3),'-',SUBSTRING(TLNO, 4, 4),'-',RIGHT(TLNO, 4)) 전화번호
FROM (
    SELECT WRITER_ID FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(DISTINCT BOARD_ID) >= 3
) BOARD
INNER JOIN USED_GOODS_USER
ON WRITER_ID = USER_ID
ORDER BY USER_ID DESC;