-- 코드를 입력하세요
SELECT i.animal_id, O.ANIMAL_TYPE, O.name FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%' AND SEX_UPON_OUTCOME NOT LIKE 'Intact%'