-- 코드를 입력하세요
#SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%#d') AS REVIEW_DATE



SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW
INNER JOIN MEMBER_PROFILE
ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID


WHERE REST_REVIEW.MEMBER_ID = (SELECT MEMBER_ID FROM (
        SELECT MEMBER_PROFILE.MEMBER_ID,REVIEW_DATE, REVIEW_TEXT, COUNT(REST_REVIEW.MEMBER_ID) AS C FROM REST_REVIEW
    INNER JOIN MEMBER_PROFILE
    ON REST_REVIEW.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
    GROUP BY REST_REVIEW.MEMBER_ID
    ORDER BY C DESC , REVIEW_DATE, REVIEW_TEXT
    LIMIT 1
    )BEST
)

ORDER BY REVIEW_DATE, REVIEW_TEXT;
